FROM golang:1-alpine3.9
MAINTAINER Ben Johnson <ben@timber.io>
ENV LANG C.UTF-8
RUN apk add --no-cache \
  curl \
  ca-certificates \
  docker \
  gnupg \
  git \
  make \
  python \
  sed \
  openssh-client \
  tar

RUN curl -O https://bootstrap.pypa.io/get-pip.py \
  && python get-pip.py \
  && rm get-pip.py
RUN pip install awscli

RUN curl -fsSL https://github.com/timberio/grease/releases/download/v1.0.1/grease-1.0.1-linux-amd64.tar.gz -o /tmp/grease.tar.gz \
  && tar -xzf /tmp/grease.tar.gz -C /tmp \
  && mv /tmp/grease/bin/grease /usr/bin/grease \
  && chown root:root /usr/bin/grease \
  && rm /tmp/grease.tar.gz \
  && rm -r /tmp/grease

RUN go get github.com/mitchellh/gox
RUN go get github.com/jstemmer/go-junit-report

LABEL io.timber.golang=1.8.3 io.timber.grease=1.0.1